-- The worked example's schema (references/worked-example.md): seven tables,
-- a join table, two enums, integer cents, a nullable foreign key, a jsonb
-- bag, a slug behind a unique index, a storage-backed image and one naive
-- `timestamp`. Written as a migration is; shop.dump.sql is the same schema
-- after a round trip through Postgres and pg_dump (README.md).

create type product_status as enum ('draft', 'active', 'archived');
create type order_status as enum ('pending', 'paid', 'shipped', 'delivered', 'cancelled', 'refunded');

create table categories (
  id uuid primary key default gen_random_uuid(),
  name varchar(80) not null unique,
  created_at timestamptz not null default now()
);

create table products (
  id uuid primary key default gen_random_uuid(),
  title varchar(120) not null,
  slug text not null,
  price_cents integer not null check (price_cents >= 0),
  currency char(3) not null default 'USD',
  status product_status not null default 'draft',
  category_id uuid references categories (id) on delete set null,
  cover_image_url text,
  metadata jsonb not null default '{}'::jsonb,
  is_featured boolean not null default false,
  available_on date,
  created_at timestamptz not null default now()
);
create unique index products_slug_key on products (slug);

create table tags (
  id bigint generated by default as identity primary key,
  name varchar(40) not null unique
);

create table product_tags (
  product_id uuid not null references products (id) on delete cascade,
  tag_id bigint not null references tags (id) on delete cascade,
  primary key (product_id, tag_id)
);

create table customers (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null unique,
  full_name varchar(120) not null,
  created_at timestamptz not null default now()
);

create table orders (
  id bigint generated always as identity primary key,
  customer_id uuid not null references customers (id) on delete cascade,
  status order_status not null default 'pending',
  total_cents integer not null check (total_cents >= 0),
  placed_at timestamp not null default now(),
  notes text check (char_length(notes) <= 500)
);

create table order_items (
  id bigint generated always as identity primary key,
  order_id bigint not null references orders (id) on delete cascade,
  product_id uuid not null references products (id),
  quantity integer not null check (quantity between 1 and 99),
  unit_price_cents integer not null check (unit_price_cents >= 0)
);

alter table categories enable row level security;
alter table products enable row level security;
alter table tags enable row level security;
alter table product_tags enable row level security;
alter table customers enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;

create policy "categories are public" on categories for select using (true);
create policy "active products are public" on products for select using (status = 'active');
create policy "tags are public" on tags for select using (true);
create policy "product tags are public" on product_tags for select using (true);
create policy "own customer row" on customers for all to authenticated
  using (id = (select auth.uid()));
create policy "own orders" on orders for select to authenticated
  using (customer_id = (select auth.uid()));
create policy "place own orders" on orders for insert to authenticated
  with check (customer_id = (select auth.uid()));
create policy "own order items" on order_items for select to authenticated
  using (exists (select 1 from orders o where o.id = order_id and o.customer_id = (select auth.uid())));
