"""The schema tool on what Postgres and Supabase actually write (DL-A7, DL-C2,
DL-B8). fixtures/supabase/README.md says where each file came from.

Regressions covered:
- DL-A7: in a dump made with `--quote-all-identifiers` (the format of
  `supabase db pull`), `"text"`, `"date"` and `"public"."order_status"` were
  unknown types, so titles fell back to the id, dates became text inputs and
  enums lost their values; identity added by `ALTER TABLE … ADD GENERATED`
  was missed, so every bigint id was an editable, required number. In
  generated types, prettier's wrapped union kept only its first value, and a
  Row column whose type wrapped was dropped.
- `generated by default as identity` in a migration read as an editable id,
  and `CHECK (x between 1 and 99)` gave no min or max.
- DL-B8: the fixture the worked example and supabase-integration.md §1 quote
  was not shipped, so neither could be checked.
"""
from __future__ import annotations

import json
import pathlib
import re

from wds_support import PLUGIN, TempDirTest, output, run_py

FIXTURES = pathlib.Path(__file__).resolve().parent / "fixtures" / "supabase"
REFERENCES = PLUGIN / "skills" / "content-model-to-ui" / "references"


class SchemaSources(TempDirTest):

    def introspect(self, *sources, summary=False):
        out = f"model{len(list(self.tmp.glob('model*.json')))}.json"
        args = [str(FIXTURES / s) if (FIXTURES / s).exists() else s for s in sources]
        proc = run_py("content-model-to-ui", "introspect_schema", *args, "-o", out,
                      *(["--summary"] if summary else []), cwd=self.tmp)
        self.assertEqual(proc.returncode, 0, output(proc))
        model = json.loads((self.tmp / out).read_text(encoding="utf-8"))
        return (model, proc.stdout.decode("utf-8")) if summary else model


def columns(model):
    return {f"{t['name']}.{c['name']}": c for t in model["tables"] for c in t["columns"]}


def rules(column):
    return sorted((r["rule"], r["value"]) for r in column["ui"].get("validation", []))


def facts(column):
    """What the screens are built from, without the way a source spells it."""
    fk = column["foreign_key"]
    ui = column["ui"]
    return {
        "type": column["type"], "nullable": column["nullable"], "enum": column["enum"],
        "primary_key": column["primary_key"], "generated": column["generated"],
        "unique": column["unique"], "is_array": column["is_array"],
        "max_length": column["max_length"],
        "foreign_key": fk and (fk["table"], fk["column"], fk["on_delete"]),
        "control": ui.get("control"), "placement": ui.get("placement"),
        "editable": ui.get("editable"), "rules": rules(column),
    }


def structure(model):
    return {t["name"]: (t["kind"], t["primary_key"],
                        sorted((r["kind"], r["to"], r["via"]) for r in t["relationships"]))
            for t in model["tables"]}


class APgDumpReadsAsTheMigrationDoes(SchemaSources):
    """DL-A7 and DL-C2: shop.dump.sql is shop.sql after Postgres and pg_dump."""

    def test_every_column_and_table_agrees(self):
        migration, dump = self.introspect("shop.sql"), self.introspect("shop.dump.sql")
        self.assertEqual(structure(migration), structure(dump))
        self.assertEqual(migration["enums"], dump["enums"])
        a, b = columns(migration), columns(dump)
        self.assertEqual(sorted(a), sorted(b))
        for name in a:
            with self.subTest(column=name):
                self.assertEqual(facts(a[name]), facts(b[name]))

    def test_db_pull_reads_as_the_dump(self):
        # supabase/cli dump_schema.sh: the same pg_dump, then these seds.
        text = (FIXTURES / "shop.dump.sql").read_text(encoding="utf-8")
        text = re.sub(r"(?m)^\\(un)?restrict .*$", r"-- \g<0>", text)
        text = re.sub(r'(?m)^CREATE TABLE "', 'CREATE TABLE IF NOT EXISTS "', text)
        self.write("pull.sql", text)
        dump, pull = columns(self.introspect("shop.dump.sql")), columns(self.introspect("pull.sql"))
        self.assertEqual({k: facts(c) for k, c in dump.items()}, {k: facts(c) for k, c in pull.items()})

    def test_the_dump_names_what_the_review_saw_misread(self):
        dump = columns(self.introspect("shop.dump.sql"))
        self.assertEqual("text-input", dump["products.title"]["ui"]["control"])
        self.assertEqual("date-picker", dump["products.available_on"]["ui"]["control"])
        self.assertEqual(("order_status", "order_status"), (dump["orders.status"]["type"],
                                                            dump["orders.status"]["enum"]))
        self.assertEqual("select", dump["orders.status"]["ui"]["control"])
        for name in ("tags.id", "orders.id", "order_items.id"):
            with self.subTest(column=name):
                self.assertTrue(dump[name]["generated"])
                self.assertFalse(dump[name]["ui"]["placement"]["form"])

    def test_the_security_pass_reads_the_dump_as_the_migration(self):
        (migration, m_out), (dump, d_out) = (self.introspect("shop.sql", summary=True),
                                             self.introspect("shop.dump.sql", summary=True))
        for t in migration["tables"]:
            with self.subTest(table=t["name"]):
                d = next(x for x in dump["tables"] if x["name"] == t["name"])
                self.assertTrue(d["rls"])
                self.assertEqual(sorted((p["name"], p["command"], p["roles"]) for p in t["policies"]),
                                 sorted((p["name"], p["command"], p["roles"]) for p in d["policies"]))
        # A dump lists the tables alphabetically.
        key = lambda f: (f["table"], f["code"])                           # noqa: E731
        self.assertEqual(sorted(migration["security"]["findings"], key=key),
                         sorted(dump["security"]["findings"], key=key))
        def block(out):
            lines = out.splitlines()
            return sorted(lines[:lines.index("")])

        self.assertEqual(block(m_out), block(d_out))
        self.assertEqual(8, len(block(d_out)))                            # a heading and seven tables

    def test_a_dump_does_not_split_a_function_body(self):
        # pg_dump writes functions with `$$` bodies, whose `;` end nothing.
        body = ("CREATE FUNCTION public.f() RETURNS trigger LANGUAGE plpgsql AS $$\n"
                "begin\n  alter table public.notes disable row level security;\n"
                "  revoke update on public.notes from authenticated;\n  return new;\nend;\n$$;\n")
        self.write("schema.sql", "\\restrict abc\n" + "CREATE TABLE public.notes (id uuid PRIMARY KEY, "
                   "body text NOT NULL);\nALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;\n"
                   + body + "\\unrestrict abc\n")
        model = self.introspect("schema.sql")
        self.assertTrue(model["tables"][0]["rls"])
        self.assertIsNone(model["tables"][0]["update_columns"])


class MigrationsThatDumpsRewrite(SchemaSources):

    def test_identity_by_default_is_generated(self):
        self.write("schema.sql", "create table t (id bigint generated by default as identity primary key, "
                   "name text not null);\n")
        id_ = columns(self.introspect("schema.sql"))["t.id"]
        self.assertTrue(id_["generated"])
        self.assertNotIn(("required", True), rules(id_))

    def test_a_sequence_default_set_later_is_generated(self):
        # How a dump writes a `serial` column.
        self.write("schema.sql", 'CREATE TABLE "public"."t" ("id" integer NOT NULL, "name" "text" NOT NULL);\n'
                   'ALTER TABLE ONLY "public"."t" ALTER COLUMN "id" SET DEFAULT '
                   "\"nextval\"('\"public\".\"t_id_seq\"'::\"regclass\");\n")
        id_ = columns(self.introspect("schema.sql"))["t.id"]
        self.assertTrue(id_["generated"])
        self.assertFalse(id_["ui"]["placement"]["form"])

    def test_columns_added_and_changed_later_are_replayed(self):
        # Migrations are read in order (N14); a column added later was dropped.
        self.write("schema.sql", "create table t (id uuid primary key, legacy text, title text);\n"
                   "alter table t add column published_on date, add if not exists slug text not null;\n"
                   "alter table only public.t drop column legacy, alter column title set not null;\n"
                   "alter table t add constraint t_slug_key unique (slug);\n"
                   "alter table t rename column published_on to released_on;\n"
                   "create table draft_posts (id uuid primary key, t_id uuid references t (id));\n"
                   "alter table t rename to posts;\n"
                   "alter table posts rename released_on to published_on;\n")
        model = self.introspect("schema.sql")
        cols = columns(model)
        self.assertEqual(["draft_posts.id", "draft_posts.t_id", "posts.id", "posts.published_on",
                          "posts.slug", "posts.title"], sorted(cols))
        self.assertEqual("posts", cols["draft_posts.t_id"]["foreign_key"]["table"])
        cols = {k.replace("posts.", "t.", 1) if k.startswith("posts.") else k: c for k, c in cols.items()}
        self.assertEqual("date-picker", cols["t.published_on"]["ui"]["control"])
        self.assertFalse(cols["t.title"]["nullable"])
        self.assertTrue(cols["t.slug"]["unique"])

    def test_between_is_a_min_and_a_max(self):
        quantity = columns(self.introspect("shop.sql"))["order_items.quantity"]
        self.assertIn(("min", 1), rules(quantity))
        self.assertIn(("max", 99), rules(quantity))

    def test_a_quoted_name_that_needs_its_quotes_keeps_them(self):
        self.write("schema.sql", 'CREATE TABLE "Mixed Case" ("Display Name" "text" NOT NULL, '
                   '"order" integer, "id" "uuid" NOT NULL);\n')
        model = self.introspect("schema.sql")
        self.assertEqual("Mixed Case", model["tables"][0]["name"])
        self.assertEqual({"Mixed Case.Display Name": "text", "Mixed Case.order": "integer",
                          "Mixed Case.id": "uuid"},
                         {k: c["type"] for k, c in columns(model).items()})

    def test_a_quoted_name_with_a_dollar_is_read(self):
        # N16: a dump quotes every name, and `$` was unquoted into a name the column
        # parser, which reads word characters, dropped without a word.
        self.write("schema.sql", 'CREATE TABLE "public"."t" ("id" "uuid" NOT NULL, '
                   '"amount$usd" integer NOT NULL);\n'
                   'ALTER TABLE ONLY "public"."t" ALTER COLUMN "amount$usd" SET DEFAULT 0;\n')
        cols = columns(self.introspect("schema.sql"))
        self.assertEqual(["t.amount$usd", "t.id"], sorted(cols))
        self.assertEqual(("integer", False, "0"), (cols["t.amount$usd"]["type"],
                                                   cols["t.amount$usd"]["nullable"],
                                                   cols["t.amount$usd"]["default"]))

    def test_dropping_a_column_drops_what_uses_it(self):
        # N17: Postgres drops every index and constraint that uses the column, the
        # whole primary key included; another table's foreign key needs CASCADE,
        # which drops it as well.
        self.write("schema.sql",
                   "create table a (id uuid primary key, code text unique, region text,"
                   " qty int check (qty > 0 or code is null));\n"
                   "create unique index a_code_region on a (code, region);\n"
                   "create unique index a_region on a (region);\n"
                   "create table b (id uuid primary key, a_code text references a (code));\n"
                   "create table pairs (x uuid, y uuid, label text, primary key (x, y));\n"
                   "alter table a drop column code cascade;\n"
                   "alter table pairs drop column x;\n")
        model = self.introspect("schema.sql")
        tables = {t["name"]: t for t in model["tables"]}
        self.assertEqual([["region"]], tables["a"]["unique_indexes"])
        self.assertEqual([], columns(model)["a.qty"]["checks"])
        self.assertIsNone(columns(model)["b.a_code"]["foreign_key"])
        self.assertEqual([], tables["b"]["relationships"])
        self.assertEqual([], tables["pairs"]["primary_key"])
        self.assertFalse(columns(model)["pairs.y"]["primary_key"])

    def test_renaming_a_column_renames_what_names_it(self):
        # N18: Postgres retargets other tables' foreign keys and rewrites the CHECKs.
        self.write("schema.sql",
                   "create table a (id uuid primary key, code text unique check (code <> 'code'),"
                   " qty int, check (qty > 0));\n"
                   "create table b (id uuid primary key, a_code text references a (code));\n"
                   "alter table a rename column code to sku;\n"
                   "alter table a rename qty to amount;\n")
        cols = columns(self.introspect("schema.sql"))
        self.assertEqual(("a", "sku"), (cols["b.a_code"]["foreign_key"]["table"],
                                        cols["b.a_code"]["foreign_key"]["column"]))
        self.assertEqual(["sku <> 'code'"], cols["a.sku"]["checks"])
        self.assertEqual(["amount > 0"], cols["a.amount"]["checks"])
        self.assertIn(("exclusiveMin", 0), rules(cols["a.amount"]))

    def test_a_not_null_constraint_is_not_a_column(self):
        # N19: Postgres 18 names a not-null constraint; the parser read the
        # unknown ADD CONSTRAINT as ADD COLUMN, and made a column named `constraint`.
        self.write("schema.sql",
                   "create table t (id uuid primary key, name text, nick text, bio text,"
                   " constraint t_bio_nn not null bio);\n"
                   "alter table t add constraint t_name_nn not null name;\n"
                   "alter table t add not null nick;\n"
                   "alter table t add constraint t_wat exclusion of some future kind;\n")
        cols = columns(self.introspect("schema.sql"))
        self.assertEqual(["t.bio", "t.id", "t.name", "t.nick"], sorted(cols))
        for name in ("t.bio", "t.name", "t.nick"):
            with self.subTest(column=name):
                self.assertFalse(cols[name]["nullable"])


class GeneratedTypesAgreeOnStructure(SchemaSources):
    """supabase-integration.md §1, as a test: what the generated types keep,
    and what they lose, against the DDL of the same schema."""

    def test_the_wrapped_enum_keeps_every_value(self):
        types = self.introspect("shop.types.ts")
        self.assertEqual(["pending", "paid", "shipped", "delivered", "cancelled", "refunded"],
                         types["enums"]["order_status"])

    def test_a_wrapped_row_column_is_read(self):
        self.write("database.types.ts", """\
export type Database = {
  public: {
    Tables: {
      orders: {
        Row: {
          fulfillment_status:
            | Database["public"]["Enums"]["fulfillment_status"]
            | null
          id: string
        }
        Insert: { id?: string }
        Update: { id?: string }
        Relationships: []
      }
    }
    Enums: {
      fulfillment_status: "unfulfilled" | "partial" | "fulfilled"
    }
  }
}
""")
        column = columns(self.introspect("database.types.ts"))["orders.fulfillment_status"]
        self.assertEqual(("enum", "fulfillment_status", True),
                         (column["type"], column["enum"], column["nullable"]))

    def test_the_structure_is_the_same_and_the_losses_are_the_documented_ones(self):
        ddl, types = self.introspect("shop.sql"), self.introspect("shop.types.ts")
        self.assertEqual(ddl["enums"], types["enums"])
        a, b = columns(ddl), columns(types)
        self.assertEqual(sorted(a), sorted(b))
        # A key into a schema the API does not expose is not in Relationships:
        # the types show `customers.id` as a plain string the form must ask for.
        hidden_keys = {name for name, c in a.items() if c["foreign_key"] and not b[name]["foreign_key"]}
        self.assertEqual({"customers.id"}, hidden_keys)
        self.assertEqual("users", a["customers.id"]["foreign_key"]["table"])
        same = ("nullable", "enum", "control")
        for name in set(a) - hidden_keys:
            with self.subTest(column=name):
                self.assertEqual({k: facts(a[name])[k] for k in same},
                                 {k: facts(b[name])[k] for k in same})
                self.assertEqual(a[name]["ui"]["placement"]["list"], b[name]["ui"]["placement"]["list"])
                fk_a, fk_b = a[name]["foreign_key"], b[name]["foreign_key"]
                if fk_a:
                    self.assertEqual((fk_a["table"], fk_a["column"]), (fk_b["table"], fk_b["column"]))
        # Join-table detection and many-to-many edges survive; ownership does not.
        kinds = {name: (kind, [r for r in rels if r[0] == "many-to-many"])
                 for name, (kind, _, rels) in structure(ddl).items()}
        self.assertEqual(kinds, {name: (kind, [r for r in rels if r[0] == "many-to-many"])
                                 for name, (kind, _, rels) in structure(types).items()})

        def children(model):
            return {(t["name"], r["to"]): r["control"] for t in model["tables"]
                    for r in t["relationships"] if r["kind"] == "one-to-many"}

        self.assertEqual("inline-subtable", children(ddl)[("orders", "order_items")])   # ON DELETE CASCADE
        self.assertEqual({"linked-list"}, set(children(types).values()))
        self.assertEqual(set(children(ddl)), set(children(types)))

        lost = {name: sorted(set(rules(a[name])) - set(rules(b[name]))) for name in set(a) - hidden_keys}
        lost = {name: r for name, r in lost.items() if r}
        self.assertTrue(all(kind in ("maxLength", "unique", "min", "max")
                            for r in lost.values() for kind, _ in r), lost)
        text = (REFERENCES / "supabase-integration.md").read_text(encoding="utf-8")
        claim = re.search(r"\*\*(\d+) validation rules across (\d+) columns\*\*", text)
        self.assertIsNotNone(claim, "the §1 claim moved")
        self.assertEqual((int(claim.group(1)), int(claim.group(2))),
                         (sum(len(r) for r in lost.values()), len(lost)), lost)


class RealSupabaseOutput(SchemaSources):
    """brewr.types.ts is `gen types` for a real 25-table project."""

    def test_every_row_column_is_read(self):
        text = (FIXTURES / "brewr.types.ts").read_text(encoding="utf-8")
        tables = text.split("    Tables: {", 1)[1].split("\n    Views: {", 1)[0]
        expected = {}
        for m in re.finditer(r"\n      (\w+): \{\n        Row: \{\n(.*?)\n        \}", tables, re.S):
            expected[m.group(1)] = sorted(re.findall(r"^ {10}(\w+):", m.group(2), re.M))
        self.assertEqual(25, len(expected))
        model = self.introspect("brewr.types.ts")
        self.assertEqual(expected, {t["name"]: sorted(c["name"] for c in t["columns"])
                                    for t in model["tables"]})
        self.assertEqual(len(re.findall(r"foreignKeyName", tables)),
                         sum(1 for c in columns(model).values() if c["foreign_key"]))


class TheWorkedExampleIsTheFixture(SchemaSources):
    """DL-B8: worked-example.md quotes `--summary` on shop.sql."""

    def test_the_quoted_summary_is_what_the_tool_prints(self):
        doc = (REFERENCES / "worked-example.md").read_text(encoding="utf-8")
        block = doc.split("What `--summary` says about `products`", 1)[1].split("```", 2)[1]
        quoted = [" ".join(line.split()) for line in block.splitlines()
                  if re.match(r"\s+([L·][D·][F·]|rel)\s", line)]
        self.assertGreater(len(quoted), 10)
        _, out = self.introspect("shop.sql", summary=True)
        printed = {" ".join(line.split()) for line in out.splitlines()}
        self.assertEqual([], [line for line in quoted if line not in printed])
